common:
  resize:
    height: 128
    width: 128
dataset:
  input_path: C:\Users\stokes\Documents\80_Project\git_work\face_segmentation\org\images
  test_split: 0.1
prepare:
  data_id: null
  experiment_id: null
train:
  fit:
    batch_size: 3
    epochs: 10
    verbose: 1
    validation_split: 0.2
    shuffle: true
    initial_epoch: 0
    callbacks:
      ReduceLROnPlateau:
        enable: true
        hparams:
          monitor: val_loss
          factor: 0.1
          patience: 5
          verbose: 1
          mode: auto
          epsilon: 0.0001
          cooldown: 0
          min_lr: 0.00001
      ModelCheckpoint:
        enable: true
        hparams:
          filepath: null
          monitor: val_loss
          verbose: 1
          save_best_only: false
          save_weights_only: false
          mode: auto
          period: 1
  optimizer:
    SGD:
      lr: 0.01
      momentum: 0.9
      decay: 0.0005
    Adagrad:
      add: null
validate:
  input_path: ./datasets/XXXX-XXXX-XXXX/validate/x
  ground_truth_path: ./datasets/XXXX-XXXX-XXXX/validate/t
test:
  input_path: null
  output_path: null
  weight: null
predict:
  input_path: ./datasets/estimate
